/**
 * Shared mutable application state and DOM references.
 * Imported by every module that needs to read/write app state.
 */

import { DEFAULT_CANVAS_PCT, DEFAULT_SETTINGS } from './constants.js';

export const state = {
  token: localStorage.getItem('umkm_token') || '',
  user: null,
  profile: null,
  conversationId: null,
  conversationTitle: 'Percakapan baru',
  conversationMessageCount: 0,
  conversations: [],
  messages: [],
  dashboards: [],
  selectedDashboardId: null,
  currentDashboard: null,
  draftDashboard: null,
  canvasWidgets: [],
  workspaceLoaded: false,
  isWorkspaceBooting: false,
  datasetReady: false,
  schema: null,
  datasetTables: [],
  grid: null,
  isDemoSession: false,
  canvasOpen: false,
  selectedWidgetId: null,
  editMode: false,
  pendingMessageId: null,
  timelineMessageId: null,
  timelineRunId: null,
  agentDialogueOpen: false,
  agentDialogueMessageId: null,
  agentDialogueItems: [],
  agentDialogueReturnFocus: null,
  canvasPage: 1,
  canvasPagesCount: 1,
  canvasWidthPct: DEFAULT_CANVAS_PCT,
  isResizingPanels: false,
  stageZoom: 1,
  settings: { ...DEFAULT_SETTINGS },
  settingsGroup: 'user',
  settingsOpen: false,
  settingsReturnFocus: null,
  sessionRailCollapsed: true,
  openConversationMenuId: null,
  dataPaneCollapsed: true,
  configPaneCollapsed: true,
  widgetBuilderOpen: false,
  widgetBuilderStep: 'type',
  widgetBuilderSelection: {
    visualization: null,
    datasetId: null,
    axes: {},
  },
  widgetBuilderActiveAxis: null,
  preChatTickerIndex: 0,
  preChatTickerInterval: null,
  preChatTickerSwapTimer: null,
  preChatTickerKey: '',
  isProgrammaticGridUpdate: false,
  isRenderingCanvas: false,
  isCanvasPreparing: false,
  isLoadingConversation: false,
  isSendingMessage: false,
  isUploadingDataset: false,
  dragDepth: 0,
  canvasViewportMovedByUser: false,
  canvasAutoCenteredRunId: null,
  draftSaveDirty: false,
  landingRevealObserver: null,
  onboardingSlideIndex: 0,
  currentPage: 'landing',
};

export const refs = {
  appShell: document.querySelector('.app-shell'),
  appHeader: document.querySelector('.app-header'),
  headerLoginBtn: document.getElementById('headerLoginBtn'),
  headerCtaBtn: document.getElementById('headerCtaBtn'),
  brandHomeLink: document.getElementById('brandHomeLink'),
  headerSettingsBtn: document.getElementById('headerSettingsBtn'),
  editProfileBtn: document.getElementById('editProfileBtn'),
  logoutBtn: document.getElementById('logoutBtn'),
  themeToggle: document.getElementById('themeToggle'),
  settingsBackdrop: document.getElementById('settingsBackdrop'),
  settingsPanel: document.getElementById('settingsPanel'),
  settingsCloseBtn: document.getElementById('settingsCloseBtn'),
  settingsForm: document.getElementById('settingsForm'),
  settingsResetBtn: document.getElementById('settingsResetBtn'),
  settingsGroupTabs: document.getElementById('settingsGroupTabs'),
  settingsGroupUserBtn: document.getElementById('settingsGroupUserBtn'),
  settingsGroupAgentBtn: document.getElementById('settingsGroupAgentBtn'),
  settingsUserGroup: document.getElementById('settingsUserGroup'),
  settingsAgentGroup: document.getElementById('settingsAgentGroup'),
  settingsThemeMode: document.getElementById('settingsThemeMode'),
  settingsAccentColor: document.getElementById('settingsAccentColor'),
  settingsNickname: document.getElementById('settingsNickname'),
  settingsResponseStyle: document.getElementById('settingsResponseStyle'),
  settingsAssistantCharacter: document.getElementById('settingsAssistantCharacter'),
  settingsPersonalizationFocus: document.getElementById('settingsPersonalizationFocus'),
  settingsBusinessName: document.getElementById('settingsBusinessName'),
  settingsBusinessIndustry: document.getElementById('settingsBusinessIndustry'),
  settingsBusinessCity: document.getElementById('settingsBusinessCity'),
  settingsBusinessTimezone: document.getElementById('settingsBusinessTimezone'),
  settingsBusinessCurrency: document.getElementById('settingsBusinessCurrency'),
  settingsBusinessVerdictTime: document.getElementById('settingsBusinessVerdictTime'),
  agentDialogueBackdrop: document.getElementById('agentDialogueBackdrop'),
  agentDialoguePanel: document.getElementById('agentDialoguePanel'),
  agentDialogueCloseBtn: document.getElementById('agentDialogueCloseBtn'),
  agentDialogueList: document.getElementById('agentDialogueList'),
  agentDialogueTitle: document.getElementById('agentDialogueTitle'),

  landingPage: document.getElementById('landingPage'),
  authPage: document.getElementById('authPage'),
  contextPage: document.getElementById('contextPage'),
  workspacePage: document.getElementById('workspacePage'),

  landingWelcomeCta: document.getElementById('landingWelcomeCta'),
  landingWelcomeDemo: document.getElementById('landingWelcomeDemo'),
  landingCtaBottom: document.getElementById('landingCtaBottom'),
  landingTryNowBtn: document.getElementById('landingTryNowBtn'),
  landingFinalCta: document.getElementById('landingFinalCta'),
  landingScrollCue: document.getElementById('landingScrollCue'),
  landingHeroStart: document.getElementById('landingHeroStart'),

  authTabs: document.getElementById('authTabs'),
  loginForm: document.getElementById('loginForm'),
  registerForm: document.getElementById('registerForm'),
  loginPasswordInput: document.getElementById('loginPasswordInput'),
  loginPasswordToggle: document.getElementById('loginPasswordToggle'),
  registerPasswordInput: document.getElementById('registerPasswordInput'),
  registerPasswordToggle: document.getElementById('registerPasswordToggle'),
  authOnboardingSlides: Array.from(document.querySelectorAll('[data-onboarding-slide]')),
  authOnboardingDots: Array.from(document.querySelectorAll('[data-onboarding-dot]')),
  contextForm: document.getElementById('contextForm'),
  workspaceLoading: document.getElementById('workspaceLoading'),
  workspaceLoadingText: document.getElementById('workspaceLoadingText'),

  sessionRail: document.getElementById('sessionRail'),
  sessionRailPeekBtn: document.getElementById('sessionRailPeekBtn'),
  sessionRailToggleBtn: document.getElementById('sessionRailToggleBtn'),
  sessionRailToggleLabel: document.getElementById('sessionRailToggleLabel'),
  sessionList: document.getElementById('sessionList'),
  dashboardList: document.getElementById('dashboardList'),
  dashboardVersionsBtn: document.getElementById('dashboardVersionsBtn'),
  newSessionBtn: document.getElementById('newSessionBtn'),

  chatPane: document.getElementById('chatPane'),
  chatPaneHead: document.getElementById('chatPaneHead'),
  chatSubtitle: document.getElementById('chatSubtitle'),
  openCanvasBtn: document.getElementById('openCanvasBtn'),
  workspaceShell: document.querySelector('.workspace-shell'),
  panelDivider: document.getElementById('panelDivider'),
  canvasPane: document.getElementById('canvasPane'),
  canvasShell: document.querySelector('.canvas-shell'),
  canvasViewport: document.getElementById('canvasViewport'),
  canvasWorld: document.getElementById('canvasWorld'),
  canvasLoading: document.getElementById('canvasLoading'),
  uploadDropOverlay: document.getElementById('uploadDropOverlay'),
  uploadLoading: document.getElementById('uploadLoading'),
  uploadLoadingText: document.getElementById('uploadLoadingText'),

  dataGate: document.getElementById('dataGate'),
  gateUploadInput: document.getElementById('gateUploadInput'),
  gateUploadPickerBtn: document.getElementById('gateUploadPickerBtn'),
  gateUploadName: document.getElementById('gateUploadName'),
  gateDemoBtn: document.getElementById('gateDemoBtn'),

  chatMessages: document.getElementById('chatMessages'),
  preChatTicker: document.getElementById('preChatTicker'),
  typingIndicator: document.getElementById('typingIndicator'),
  quickPrompts: document.getElementById('quickPrompts'),
  chatForm: document.getElementById('chatForm'),
  chatInput: document.getElementById('chatInput'),
  chatFile: document.getElementById('chatFile'),
  chatFileBtn: document.getElementById('chatFileBtn'),
  fileLabel: document.getElementById('fileLabel'),

  persistDraftBtn: document.getElementById('persistDraftBtn'),
  saveCanvasBtn: document.getElementById('saveCanvasBtn'),
  toggleDataPaneBtn: document.getElementById('toggleDataPaneBtn'),
  toggleConfigPaneBtn: document.getElementById('toggleConfigPaneBtn'),
  addWidgetToolbar: document.getElementById('addWidgetToolbar'),
  widgetBuilderBackdrop: document.getElementById('widgetBuilderBackdrop'),
  widgetBuilderModal: document.getElementById('widgetBuilderModal'),
  widgetBuilderCloseBtn: document.getElementById('widgetBuilderCloseBtn'),
  widgetBuilderTitle: document.getElementById('widgetBuilderTitle'),
  widgetBuilderStepType: document.getElementById('widgetBuilderStepType'),
  widgetBuilderStepConfig: document.getElementById('widgetBuilderStepConfig'),
  widgetTypeGrid: document.getElementById('widgetTypeGrid'),
  widgetAxisList: document.getElementById('widgetAxisList'),
  widgetAxisHint: document.getElementById('widgetAxisHint'),
  widgetDatasetTitle: document.getElementById('widgetDatasetTitle'),
  widgetDatasetMeta: document.getElementById('widgetDatasetMeta'),
  widgetDatasetList: document.getElementById('widgetDatasetList'),
  widgetDatasetPreview: document.getElementById('widgetDatasetPreview'),
  widgetBuilderBackBtn: document.getElementById('widgetBuilderBackBtn'),
  widgetBuilderNextBtn: document.getElementById('widgetBuilderNextBtn'),
  editModeBtn: document.getElementById('editModeBtn'),
  floatingAddBtn: document.getElementById('floatingAddBtn'),
  zoomInBtn: document.getElementById('zoomInBtn'),
  zoomOutBtn: document.getElementById('zoomOutBtn'),
  zoomResetBtn: document.getElementById('zoomResetBtn'),
  zoomLevelLabel: document.getElementById('zoomLevelLabel'),
  canvasStage: document.getElementById('canvasStage'),
  canvasPrevPage: document.getElementById('canvasPrevPage'),
  canvasNextPage: document.getElementById('canvasNextPage'),
  canvasAddPage: document.getElementById('canvasAddPage'),
  canvasDeletePage: document.getElementById('canvasDeletePage'),
  canvasPageIndicator: document.getElementById('canvasPageIndicator'),
  canvasDock: document.getElementById('canvasDock'),
  canvasGrid: document.getElementById('canvasGrid'),
  sessionRailBackdrop: document.getElementById('sessionRailBackdrop'),
  sourceList: document.getElementById('sourceList'),
  dataFields: document.getElementById('dataFields'),
  dataPane: document.getElementById('dataPane'),

  configForm: document.getElementById('configForm'),
  configEmpty: document.getElementById('configEmpty'),
  configDataset: document.getElementById('configDataset'),
  configMeasure: document.getElementById('configMeasure'),
  configGroupBy: document.getElementById('configGroupBy'),
  configVisualization: document.getElementById('configVisualization'),

  statusBar: document.getElementById('statusBar'),
  verdictBadge: document.getElementById('verdictBadge'),
  sourceStats: document.getElementById('sourceStats'),
  toast: document.getElementById('toast'),
};
